/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QComboBox *com_list;
    QPushButton *bt_connect;
    QPushButton *bt_refresh;
    QGroupBox *gb_position_read;
    QLineEdit *tb_x_cur_cor;
    QLineEdit *tb_y_cur_cor;
    QLineEdit *tb_z_cur_cor;
    QLineEdit *tb_roll_cur_cor;
    QLineEdit *tb_theta1_cur_val;
    QLineEdit *tb_theta2_cur_val;
    QLineEdit *tb_d3_cur_val;
    QLineEdit *tb_theta4_cur_val;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QPushButton *bt_read_position;
    QRadioButton *rb_real_type;
    QRadioButton *rb_estimate_type;
    QCheckBox *cb_update_true_pos;
    QTextEdit *tb_console;
    QPushButton *bt_clear_console;
    QPushButton *testing;
    QGroupBox *gb_method_change;
    QRadioButton *rb_manual;
    QRadioButton *rb_auto;
    QRadioButton *rb_test;
    QRadioButton *rb_pick_and_place;
    QRadioButton *rb_semi_auto;
    QPushButton *bt_set_method;
    QTabWidget *tw_method_content;
    QWidget *tab;
    QTabWidget *tabWidget_2;
    QWidget *tab_4;
    QLabel *label_6;
    QLabel *label_2;
    QLineEdit *tb_roll_ang;
    QLabel *label_4;
    QLabel *label;
    QLabel *label_7;
    QPushButton *bt_movL;
    QLineEdit *tb_v_factor;
    QLabel *label_5;
    QLineEdit *tb_a_factor;
    QLineEdit *tb_x_cor;
    QLabel *label_3;
    QLineEdit *tb_z_cor;
    QLineEdit *tb_y_cor;
    QLineEdit *tb_time;
    QRadioButton *rb_movL;
    QRadioButton *rb_movJ;
    QWidget *tab_5;
    QLabel *label_22;
    QLineEdit *tb_roll_ang_c1;
    QLabel *lb_1;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QPushButton *bt_movC1;
    QLineEdit *tb_v_factor_c1;
    QLabel *label_27;
    QLineEdit *tb_a_factor_c1;
    QLineEdit *tb_x_cor_c1;
    QLabel *label_28;
    QLineEdit *tb_radius_cor;
    QLineEdit *tb_y_cor_c1;
    QLineEdit *tb_time_c1;
    QRadioButton *rb_cw_c1;
    QRadioButton *rb_aw_c1;
    QWidget *tab_6;
    QLabel *lb_2;
    QLineEdit *tb_y_cor_c2;
    QLineEdit *tb_v_factor_c2;
    QLineEdit *tb_x_cor_c2;
    QLabel *label_29;
    QRadioButton *rb_aw_c2;
    QLabel *label_23;
    QLabel *label_30;
    QLineEdit *tb_subpoint_x;
    QLineEdit *tb_time_c2;
    QLabel *label_31;
    QLabel *label_32;
    QPushButton *bt_movC2;
    QLineEdit *tb_a_factor_c2;
    QLabel *label_33;
    QRadioButton *rb_cw_c2;
    QLineEdit *tb_subpoint_y;
    QLineEdit *tb_roll_ang_c2;
    QLabel *label_34;
    QPushButton *bt_robot_stop;
    QGroupBox *groupBox_3;
    QRadioButton *rb_qva;
    QRadioButton *rb_qvt;
    QRadioButton *rb_qt;
    QGroupBox *groupBox_5;
    QRadioButton *rb_scur;
    QRadioButton *rb_lspb;
    QRadioButton *rb_linear;
    QGroupBox *groupBox_4;
    QRadioButton *rb_inc;
    QRadioButton *rb_abs;
    QPushButton *bt_home;
    QPushButton *bt_scan_limit;
    QWidget *tab_7;
    QLineEdit *tb_key_setsp;
    QPushButton *bt_inc_6;
    QPushButton *bt_inc_2;
    QPushButton *bt_inc_5;
    QPushButton *bt_inc_7;
    QPushButton *bt_inc_8;
    QPushButton *bt_key_setsp;
    QPushButton *bt_inc_3;
    QPushButton *bt_inc_1;
    QPushButton *bt_inc_4;
    QLabel *label_35;
    QWidget *tab_2;
    QRadioButton *rb_test_mt4;
    QRadioButton *rb_test_mt2;
    QRadioButton *rb_test_mt1;
    QRadioButton *rb_test_mt3;
    QLabel *label_17;
    QLabel *label_16;
    QSlider *hs_testmt_sign;
    QPushButton *bt_start_test;
    QPushButton *bt_stop_test;
    QPushButton *bt_model_setting;
    QLineEdit *tb_m1_pulse;
    QLineEdit *tb_m2_pulse;
    QLineEdit *tb_m3_pulse;
    QLineEdit *tb_m4_pulse;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QWidget *tab_3;
    QLineEdit *tb_file_dir;
    QPushButton *bt_browse;
    QPushButton *bt_process;
    QPushButton *bt_gcode_pause;
    QPushButton *bt_gcode_resume;
    QPushButton *bt_gcode_stop;
    QProgressBar *pb_gcode_process;
    QPushButton *bt_gcode_start;
    QLineEdit *tb_x_offset;
    QLineEdit *tb_y_offset;
    QLineEdit *tb_z_offset;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QPushButton *bt_gcode_configure;
    QLineEdit *tb_hold_roll_angle;
    QLabel *label_21;
    QLabel *label_36;
    QLabel *label_37;
    QWidget *tab_8;
    QLineEdit *tb_conveyor_sp;
    QPushButton *bt_conveyor_sp;
    QLabel *label_42;
    QLineEdit *tb_p2p_1;
    QLineEdit *tb_p2p_2;
    QLineEdit *tb_p2p_3;
    QLineEdit *tb_p2p_4;
    QLineEdit *tb_p2p_5;
    QLineEdit *tb_p2p_10;
    QLineEdit *tb_p2p_7;
    QLineEdit *tb_p2p_8;
    QLineEdit *tb_p2p_9;
    QLineEdit *tb_p2p_6;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QGroupBox *gb_output_shaft;
    QPushButton *bt_off_magnet;
    QPushButton *bt_on_magnet;
    QPushButton *bt_sw_test;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1079, 387);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        com_list = new QComboBox(centralwidget);
        com_list->setObjectName(QString::fromUtf8("com_list"));
        com_list->setGeometry(QRect(21, 10, 111, 21));
        bt_connect = new QPushButton(centralwidget);
        bt_connect->setObjectName(QString::fromUtf8("bt_connect"));
        bt_connect->setGeometry(QRect(230, 10, 80, 21));
        bt_refresh = new QPushButton(centralwidget);
        bt_refresh->setObjectName(QString::fromUtf8("bt_refresh"));
        bt_refresh->setGeometry(QRect(140, 10, 80, 21));
        gb_position_read = new QGroupBox(centralwidget);
        gb_position_read->setObjectName(QString::fromUtf8("gb_position_read"));
        gb_position_read->setGeometry(QRect(10, 30, 311, 181));
        tb_x_cur_cor = new QLineEdit(gb_position_read);
        tb_x_cur_cor->setObjectName(QString::fromUtf8("tb_x_cur_cor"));
        tb_x_cur_cor->setGeometry(QRect(10, 20, 81, 21));
        tb_y_cur_cor = new QLineEdit(gb_position_read);
        tb_y_cur_cor->setObjectName(QString::fromUtf8("tb_y_cur_cor"));
        tb_y_cur_cor->setGeometry(QRect(10, 50, 81, 21));
        tb_z_cur_cor = new QLineEdit(gb_position_read);
        tb_z_cur_cor->setObjectName(QString::fromUtf8("tb_z_cur_cor"));
        tb_z_cur_cor->setGeometry(QRect(10, 80, 81, 21));
        tb_roll_cur_cor = new QLineEdit(gb_position_read);
        tb_roll_cur_cor->setObjectName(QString::fromUtf8("tb_roll_cur_cor"));
        tb_roll_cur_cor->setGeometry(QRect(10, 110, 81, 21));
        tb_theta1_cur_val = new QLineEdit(gb_position_read);
        tb_theta1_cur_val->setObjectName(QString::fromUtf8("tb_theta1_cur_val"));
        tb_theta1_cur_val->setGeometry(QRect(160, 20, 81, 21));
        tb_theta2_cur_val = new QLineEdit(gb_position_read);
        tb_theta2_cur_val->setObjectName(QString::fromUtf8("tb_theta2_cur_val"));
        tb_theta2_cur_val->setGeometry(QRect(160, 50, 81, 21));
        tb_d3_cur_val = new QLineEdit(gb_position_read);
        tb_d3_cur_val->setObjectName(QString::fromUtf8("tb_d3_cur_val"));
        tb_d3_cur_val->setGeometry(QRect(160, 80, 81, 21));
        tb_theta4_cur_val = new QLineEdit(gb_position_read);
        tb_theta4_cur_val->setObjectName(QString::fromUtf8("tb_theta4_cur_val"));
        tb_theta4_cur_val->setGeometry(QRect(160, 110, 81, 21));
        label_8 = new QLabel(gb_position_read);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(100, 20, 47, 13));
        label_9 = new QLabel(gb_position_read);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(100, 50, 47, 13));
        label_10 = new QLabel(gb_position_read);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(100, 80, 47, 13));
        label_11 = new QLabel(gb_position_read);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(100, 110, 47, 13));
        label_12 = new QLabel(gb_position_read);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(250, 110, 47, 13));
        label_13 = new QLabel(gb_position_read);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(250, 20, 47, 13));
        label_14 = new QLabel(gb_position_read);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(250, 80, 47, 13));
        label_15 = new QLabel(gb_position_read);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(250, 50, 47, 13));
        bt_read_position = new QPushButton(gb_position_read);
        bt_read_position->setObjectName(QString::fromUtf8("bt_read_position"));
        bt_read_position->setGeometry(QRect(10, 140, 80, 21));
        rb_real_type = new QRadioButton(gb_position_read);
        rb_real_type->setObjectName(QString::fromUtf8("rb_real_type"));
        rb_real_type->setGeometry(QRect(100, 140, 71, 19));
        rb_real_type->setChecked(true);
        rb_estimate_type = new QRadioButton(gb_position_read);
        rb_estimate_type->setObjectName(QString::fromUtf8("rb_estimate_type"));
        rb_estimate_type->setGeometry(QRect(100, 160, 91, 19));
        rb_estimate_type->setChecked(false);
        cb_update_true_pos = new QCheckBox(gb_position_read);
        cb_update_true_pos->setObjectName(QString::fromUtf8("cb_update_true_pos"));
        cb_update_true_pos->setGeometry(QRect(190, 140, 121, 19));
        tb_console = new QTextEdit(centralwidget);
        tb_console->setObjectName(QString::fromUtf8("tb_console"));
        tb_console->setGeometry(QRect(830, 30, 241, 251));
        bt_clear_console = new QPushButton(centralwidget);
        bt_clear_console->setObjectName(QString::fromUtf8("bt_clear_console"));
        bt_clear_console->setGeometry(QRect(830, 0, 80, 21));
        testing = new QPushButton(centralwidget);
        testing->setObjectName(QString::fromUtf8("testing"));
        testing->setGeometry(QRect(980, 0, 80, 21));
        gb_method_change = new QGroupBox(centralwidget);
        gb_method_change->setObjectName(QString::fromUtf8("gb_method_change"));
        gb_method_change->setGeometry(QRect(330, 10, 491, 331));
        rb_manual = new QRadioButton(gb_method_change);
        rb_manual->setObjectName(QString::fromUtf8("rb_manual"));
        rb_manual->setGeometry(QRect(90, 20, 61, 19));
        rb_auto = new QRadioButton(gb_method_change);
        rb_auto->setObjectName(QString::fromUtf8("rb_auto"));
        rb_auto->setGeometry(QRect(200, 20, 61, 19));
        rb_test = new QRadioButton(gb_method_change);
        rb_test->setObjectName(QString::fromUtf8("rb_test"));
        rb_test->setGeometry(QRect(150, 20, 51, 19));
        rb_pick_and_place = new QRadioButton(gb_method_change);
        rb_pick_and_place->setObjectName(QString::fromUtf8("rb_pick_and_place"));
        rb_pick_and_place->setGeometry(QRect(260, 20, 111, 17));
        rb_semi_auto = new QRadioButton(gb_method_change);
        rb_semi_auto->setObjectName(QString::fromUtf8("rb_semi_auto"));
        rb_semi_auto->setGeometry(QRect(10, 20, 81, 19));
        rb_semi_auto->setChecked(true);
        bt_set_method = new QPushButton(gb_method_change);
        bt_set_method->setObjectName(QString::fromUtf8("bt_set_method"));
        bt_set_method->setGeometry(QRect(370, 20, 101, 21));
        tw_method_content = new QTabWidget(gb_method_change);
        tw_method_content->setObjectName(QString::fromUtf8("tw_method_content"));
        tw_method_content->setGeometry(QRect(10, 40, 471, 281));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tabWidget_2 = new QTabWidget(tab);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(0, 0, 371, 181));
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_6 = new QLabel(tab_4);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(290, 10, 61, 16));
        label_2 = new QLabel(tab_4);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(130, 10, 47, 13));
        tb_roll_ang = new QLineEdit(tab_4);
        tb_roll_ang->setObjectName(QString::fromUtf8("tb_roll_ang"));
        tb_roll_ang->setGeometry(QRect(0, 100, 113, 21));
        label_4 = new QLabel(tab_4);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(130, 70, 47, 13));
        label = new QLabel(tab_4);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(130, 40, 47, 13));
        label_7 = new QLabel(tab_4);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(290, 70, 47, 13));
        bt_movL = new QPushButton(tab_4);
        bt_movL->setObjectName(QString::fromUtf8("bt_movL"));
        bt_movL->setGeometry(QRect(170, 100, 61, 21));
        tb_v_factor = new QLineEdit(tab_4);
        tb_v_factor->setObjectName(QString::fromUtf8("tb_v_factor"));
        tb_v_factor->setGeometry(QRect(170, 10, 113, 21));
        label_5 = new QLabel(tab_4);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(290, 40, 47, 13));
        tb_a_factor = new QLineEdit(tab_4);
        tb_a_factor->setObjectName(QString::fromUtf8("tb_a_factor"));
        tb_a_factor->setGeometry(QRect(170, 40, 113, 21));
        tb_x_cor = new QLineEdit(tab_4);
        tb_x_cor->setObjectName(QString::fromUtf8("tb_x_cor"));
        tb_x_cor->setGeometry(QRect(0, 10, 113, 21));
        label_3 = new QLabel(tab_4);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(120, 100, 47, 13));
        tb_z_cor = new QLineEdit(tab_4);
        tb_z_cor->setObjectName(QString::fromUtf8("tb_z_cor"));
        tb_z_cor->setGeometry(QRect(0, 70, 113, 21));
        tb_y_cor = new QLineEdit(tab_4);
        tb_y_cor->setObjectName(QString::fromUtf8("tb_y_cor"));
        tb_y_cor->setGeometry(QRect(0, 40, 113, 21));
        tb_time = new QLineEdit(tab_4);
        tb_time->setObjectName(QString::fromUtf8("tb_time"));
        tb_time->setGeometry(QRect(170, 70, 113, 21));
        rb_movL = new QRadioButton(tab_4);
        rb_movL->setObjectName(QString::fromUtf8("rb_movL"));
        rb_movL->setGeometry(QRect(240, 100, 51, 19));
        rb_movL->setChecked(true);
        rb_movJ = new QRadioButton(tab_4);
        rb_movJ->setObjectName(QString::fromUtf8("rb_movJ"));
        rb_movJ->setGeometry(QRect(290, 100, 51, 19));
        tabWidget_2->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        label_22 = new QLabel(tab_5);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(140, 10, 47, 13));
        tb_roll_ang_c1 = new QLineEdit(tab_5);
        tb_roll_ang_c1->setObjectName(QString::fromUtf8("tb_roll_ang_c1"));
        tb_roll_ang_c1->setGeometry(QRect(10, 100, 113, 21));
        lb_1 = new QLabel(tab_5);
        lb_1->setObjectName(QString::fromUtf8("lb_1"));
        lb_1->setGeometry(QRect(130, 70, 47, 13));
        label_24 = new QLabel(tab_5);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(140, 40, 47, 13));
        label_25 = new QLabel(tab_5);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(300, 70, 47, 13));
        label_26 = new QLabel(tab_5);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(300, 10, 61, 16));
        bt_movC1 = new QPushButton(tab_5);
        bt_movC1->setObjectName(QString::fromUtf8("bt_movC1"));
        bt_movC1->setGeometry(QRect(180, 100, 80, 21));
        tb_v_factor_c1 = new QLineEdit(tab_5);
        tb_v_factor_c1->setObjectName(QString::fromUtf8("tb_v_factor_c1"));
        tb_v_factor_c1->setGeometry(QRect(180, 10, 113, 21));
        label_27 = new QLabel(tab_5);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(300, 40, 47, 13));
        tb_a_factor_c1 = new QLineEdit(tab_5);
        tb_a_factor_c1->setObjectName(QString::fromUtf8("tb_a_factor_c1"));
        tb_a_factor_c1->setGeometry(QRect(180, 40, 113, 21));
        tb_x_cor_c1 = new QLineEdit(tab_5);
        tb_x_cor_c1->setObjectName(QString::fromUtf8("tb_x_cor_c1"));
        tb_x_cor_c1->setGeometry(QRect(10, 10, 113, 21));
        label_28 = new QLabel(tab_5);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(130, 100, 47, 13));
        tb_radius_cor = new QLineEdit(tab_5);
        tb_radius_cor->setObjectName(QString::fromUtf8("tb_radius_cor"));
        tb_radius_cor->setGeometry(QRect(10, 70, 113, 21));
        tb_y_cor_c1 = new QLineEdit(tab_5);
        tb_y_cor_c1->setObjectName(QString::fromUtf8("tb_y_cor_c1"));
        tb_y_cor_c1->setGeometry(QRect(10, 40, 113, 21));
        tb_time_c1 = new QLineEdit(tab_5);
        tb_time_c1->setObjectName(QString::fromUtf8("tb_time_c1"));
        tb_time_c1->setGeometry(QRect(180, 70, 113, 21));
        rb_cw_c1 = new QRadioButton(tab_5);
        rb_cw_c1->setObjectName(QString::fromUtf8("rb_cw_c1"));
        rb_cw_c1->setGeometry(QRect(30, 130, 71, 19));
        rb_cw_c1->setChecked(true);
        rb_aw_c1 = new QRadioButton(tab_5);
        rb_aw_c1->setObjectName(QString::fromUtf8("rb_aw_c1"));
        rb_aw_c1->setGeometry(QRect(100, 130, 71, 19));
        tabWidget_2->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        lb_2 = new QLabel(tab_6);
        lb_2->setObjectName(QString::fromUtf8("lb_2"));
        lb_2->setGeometry(QRect(130, 70, 51, 16));
        tb_y_cor_c2 = new QLineEdit(tab_6);
        tb_y_cor_c2->setObjectName(QString::fromUtf8("tb_y_cor_c2"));
        tb_y_cor_c2->setGeometry(QRect(10, 40, 113, 21));
        tb_v_factor_c2 = new QLineEdit(tab_6);
        tb_v_factor_c2->setObjectName(QString::fromUtf8("tb_v_factor_c2"));
        tb_v_factor_c2->setGeometry(QRect(180, 10, 113, 21));
        tb_x_cor_c2 = new QLineEdit(tab_6);
        tb_x_cor_c2->setObjectName(QString::fromUtf8("tb_x_cor_c2"));
        tb_x_cor_c2->setGeometry(QRect(10, 10, 113, 21));
        label_29 = new QLabel(tab_6);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(140, 40, 47, 13));
        rb_aw_c2 = new QRadioButton(tab_6);
        rb_aw_c2->setObjectName(QString::fromUtf8("rb_aw_c2"));
        rb_aw_c2->setGeometry(QRect(100, 130, 71, 19));
        label_23 = new QLabel(tab_6);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(140, 10, 47, 13));
        label_30 = new QLabel(tab_6);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(310, 70, 47, 13));
        tb_subpoint_x = new QLineEdit(tab_6);
        tb_subpoint_x->setObjectName(QString::fromUtf8("tb_subpoint_x"));
        tb_subpoint_x->setGeometry(QRect(10, 70, 113, 21));
        tb_time_c2 = new QLineEdit(tab_6);
        tb_time_c2->setObjectName(QString::fromUtf8("tb_time_c2"));
        tb_time_c2->setGeometry(QRect(190, 70, 113, 21));
        label_31 = new QLabel(tab_6);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(130, 100, 51, 16));
        label_32 = new QLabel(tab_6);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(300, 40, 47, 13));
        bt_movC2 = new QPushButton(tab_6);
        bt_movC2->setObjectName(QString::fromUtf8("bt_movC2"));
        bt_movC2->setGeometry(QRect(190, 130, 80, 21));
        tb_a_factor_c2 = new QLineEdit(tab_6);
        tb_a_factor_c2->setObjectName(QString::fromUtf8("tb_a_factor_c2"));
        tb_a_factor_c2->setGeometry(QRect(180, 40, 113, 21));
        label_33 = new QLabel(tab_6);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(300, 10, 61, 16));
        rb_cw_c2 = new QRadioButton(tab_6);
        rb_cw_c2->setObjectName(QString::fromUtf8("rb_cw_c2"));
        rb_cw_c2->setGeometry(QRect(30, 130, 71, 19));
        rb_cw_c2->setChecked(true);
        tb_subpoint_y = new QLineEdit(tab_6);
        tb_subpoint_y->setObjectName(QString::fromUtf8("tb_subpoint_y"));
        tb_subpoint_y->setGeometry(QRect(10, 100, 113, 21));
        tb_roll_ang_c2 = new QLineEdit(tab_6);
        tb_roll_ang_c2->setObjectName(QString::fromUtf8("tb_roll_ang_c2"));
        tb_roll_ang_c2->setGeometry(QRect(190, 100, 113, 21));
        label_34 = new QLabel(tab_6);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(310, 100, 47, 13));
        tabWidget_2->addTab(tab_6, QString());
        bt_robot_stop = new QPushButton(tab);
        bt_robot_stop->setObjectName(QString::fromUtf8("bt_robot_stop"));
        bt_robot_stop->setGeometry(QRect(380, 30, 80, 21));
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 190, 141, 41));
        rb_qva = new QRadioButton(groupBox_3);
        rb_qva->setObjectName(QString::fromUtf8("rb_qva"));
        rb_qva->setGeometry(QRect(50, 20, 51, 19));
        rb_qvt = new QRadioButton(groupBox_3);
        rb_qvt->setObjectName(QString::fromUtf8("rb_qvt"));
        rb_qvt->setGeometry(QRect(0, 20, 41, 19));
        rb_qvt->setCheckable(true);
        rb_qvt->setChecked(true);
        rb_qt = new QRadioButton(groupBox_3);
        rb_qt->setObjectName(QString::fromUtf8("rb_qt"));
        rb_qt->setGeometry(QRect(100, 20, 41, 19));
        groupBox_5 = new QGroupBox(tab);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(150, 190, 161, 41));
        rb_scur = new QRadioButton(groupBox_5);
        rb_scur->setObjectName(QString::fromUtf8("rb_scur"));
        rb_scur->setGeometry(QRect(50, 20, 61, 19));
        rb_lspb = new QRadioButton(groupBox_5);
        rb_lspb->setObjectName(QString::fromUtf8("rb_lspb"));
        rb_lspb->setGeometry(QRect(0, 20, 51, 19));
        rb_lspb->setChecked(true);
        rb_linear = new QRadioButton(groupBox_5);
        rb_linear->setObjectName(QString::fromUtf8("rb_linear"));
        rb_linear->setGeometry(QRect(110, 20, 51, 19));
        groupBox_4 = new QGroupBox(tab);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(320, 190, 151, 41));
        rb_inc = new QRadioButton(groupBox_4);
        rb_inc->setObjectName(QString::fromUtf8("rb_inc"));
        rb_inc->setGeometry(QRect(0, 20, 84, 19));
        rb_abs = new QRadioButton(groupBox_4);
        rb_abs->setObjectName(QString::fromUtf8("rb_abs"));
        rb_abs->setGeometry(QRect(80, 20, 84, 19));
        rb_abs->setChecked(true);
        bt_home = new QPushButton(tab);
        bt_home->setObjectName(QString::fromUtf8("bt_home"));
        bt_home->setGeometry(QRect(380, 110, 80, 21));
        bt_scan_limit = new QPushButton(tab);
        bt_scan_limit->setObjectName(QString::fromUtf8("bt_scan_limit"));
        bt_scan_limit->setGeometry(QRect(380, 70, 80, 21));
        tw_method_content->addTab(tab, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        tb_key_setsp = new QLineEdit(tab_7);
        tb_key_setsp->setObjectName(QString::fromUtf8("tb_key_setsp"));
        tb_key_setsp->setGeometry(QRect(220, 30, 81, 21));
        bt_inc_6 = new QPushButton(tab_7);
        bt_inc_6->setObjectName(QString::fromUtf8("bt_inc_6"));
        bt_inc_6->setGeometry(QRect(110, 110, 80, 21));
        bt_inc_2 = new QPushButton(tab_7);
        bt_inc_2->setObjectName(QString::fromUtf8("bt_inc_2"));
        bt_inc_2->setGeometry(QRect(110, 30, 80, 21));
        bt_inc_5 = new QPushButton(tab_7);
        bt_inc_5->setObjectName(QString::fromUtf8("bt_inc_5"));
        bt_inc_5->setGeometry(QRect(20, 110, 80, 21));
        bt_inc_7 = new QPushButton(tab_7);
        bt_inc_7->setObjectName(QString::fromUtf8("bt_inc_7"));
        bt_inc_7->setGeometry(QRect(20, 160, 80, 21));
        bt_inc_8 = new QPushButton(tab_7);
        bt_inc_8->setObjectName(QString::fromUtf8("bt_inc_8"));
        bt_inc_8->setGeometry(QRect(110, 160, 81, 21));
        bt_key_setsp = new QPushButton(tab_7);
        bt_key_setsp->setObjectName(QString::fromUtf8("bt_key_setsp"));
        bt_key_setsp->setGeometry(QRect(220, 70, 81, 31));
        bt_inc_3 = new QPushButton(tab_7);
        bt_inc_3->setObjectName(QString::fromUtf8("bt_inc_3"));
        bt_inc_3->setGeometry(QRect(20, 70, 80, 21));
        bt_inc_1 = new QPushButton(tab_7);
        bt_inc_1->setObjectName(QString::fromUtf8("bt_inc_1"));
        bt_inc_1->setGeometry(QRect(20, 30, 80, 21));
        bt_inc_4 = new QPushButton(tab_7);
        bt_inc_4->setObjectName(QString::fromUtf8("bt_inc_4"));
        bt_inc_4->setGeometry(QRect(110, 70, 80, 21));
        label_35 = new QLabel(tab_7);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(310, 30, 91, 21));
        tw_method_content->addTab(tab_7, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        rb_test_mt4 = new QRadioButton(tab_2);
        rb_test_mt4->setObjectName(QString::fromUtf8("rb_test_mt4"));
        rb_test_mt4->setGeometry(QRect(20, 140, 61, 19));
        rb_test_mt2 = new QRadioButton(tab_2);
        rb_test_mt2->setObjectName(QString::fromUtf8("rb_test_mt2"));
        rb_test_mt2->setGeometry(QRect(20, 60, 61, 19));
        rb_test_mt1 = new QRadioButton(tab_2);
        rb_test_mt1->setObjectName(QString::fromUtf8("rb_test_mt1"));
        rb_test_mt1->setGeometry(QRect(20, 20, 61, 19));
        rb_test_mt1->setChecked(true);
        rb_test_mt3 = new QRadioButton(tab_2);
        rb_test_mt3->setObjectName(QString::fromUtf8("rb_test_mt3"));
        rb_test_mt3->setGeometry(QRect(20, 100, 61, 19));
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(390, 80, 47, 13));
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(290, 80, 47, 13));
        hs_testmt_sign = new QSlider(tab_2);
        hs_testmt_sign->setObjectName(QString::fromUtf8("hs_testmt_sign"));
        hs_testmt_sign->setGeometry(QRect(340, 80, 41, 16));
        hs_testmt_sign->setMaximum(1);
        hs_testmt_sign->setOrientation(Qt::Horizontal);
        bt_start_test = new QPushButton(tab_2);
        bt_start_test->setObjectName(QString::fromUtf8("bt_start_test"));
        bt_start_test->setGeometry(QRect(290, 40, 71, 31));
        bt_stop_test = new QPushButton(tab_2);
        bt_stop_test->setObjectName(QString::fromUtf8("bt_stop_test"));
        bt_stop_test->setGeometry(QRect(370, 40, 71, 31));
        bt_model_setting = new QPushButton(tab_2);
        bt_model_setting->setObjectName(QString::fromUtf8("bt_model_setting"));
        bt_model_setting->setGeometry(QRect(130, 170, 61, 21));
        tb_m1_pulse = new QLineEdit(tab_2);
        tb_m1_pulse->setObjectName(QString::fromUtf8("tb_m1_pulse"));
        tb_m1_pulse->setGeometry(QRect(100, 20, 91, 21));
        tb_m2_pulse = new QLineEdit(tab_2);
        tb_m2_pulse->setObjectName(QString::fromUtf8("tb_m2_pulse"));
        tb_m2_pulse->setGeometry(QRect(100, 60, 91, 21));
        tb_m3_pulse = new QLineEdit(tab_2);
        tb_m3_pulse->setObjectName(QString::fromUtf8("tb_m3_pulse"));
        tb_m3_pulse->setGeometry(QRect(100, 100, 91, 21));
        tb_m4_pulse = new QLineEdit(tab_2);
        tb_m4_pulse->setObjectName(QString::fromUtf8("tb_m4_pulse"));
        tb_m4_pulse->setGeometry(QRect(100, 140, 91, 21));
        label_38 = new QLabel(tab_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(200, 20, 71, 16));
        label_39 = new QLabel(tab_2);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(200, 60, 71, 16));
        label_40 = new QLabel(tab_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(200, 100, 71, 16));
        label_41 = new QLabel(tab_2);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(200, 140, 81, 16));
        tw_method_content->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        tb_file_dir = new QLineEdit(tab_3);
        tb_file_dir->setObjectName(QString::fromUtf8("tb_file_dir"));
        tb_file_dir->setGeometry(QRect(10, 100, 181, 21));
        bt_browse = new QPushButton(tab_3);
        bt_browse->setObjectName(QString::fromUtf8("bt_browse"));
        bt_browse->setGeometry(QRect(200, 100, 61, 21));
        bt_process = new QPushButton(tab_3);
        bt_process->setObjectName(QString::fromUtf8("bt_process"));
        bt_process->setGeometry(QRect(170, 130, 101, 21));
        bt_gcode_pause = new QPushButton(tab_3);
        bt_gcode_pause->setObjectName(QString::fromUtf8("bt_gcode_pause"));
        bt_gcode_pause->setGeometry(QRect(150, 10, 51, 21));
        bt_gcode_resume = new QPushButton(tab_3);
        bt_gcode_resume->setObjectName(QString::fromUtf8("bt_gcode_resume"));
        bt_gcode_resume->setGeometry(QRect(210, 10, 61, 21));
        bt_gcode_stop = new QPushButton(tab_3);
        bt_gcode_stop->setObjectName(QString::fromUtf8("bt_gcode_stop"));
        bt_gcode_stop->setGeometry(QRect(80, 10, 61, 21));
        pb_gcode_process = new QProgressBar(tab_3);
        pb_gcode_process->setObjectName(QString::fromUtf8("pb_gcode_process"));
        pb_gcode_process->setGeometry(QRect(10, 40, 161, 21));
        pb_gcode_process->setValue(0);
        bt_gcode_start = new QPushButton(tab_3);
        bt_gcode_start->setObjectName(QString::fromUtf8("bt_gcode_start"));
        bt_gcode_start->setGeometry(QRect(10, 10, 61, 21));
        tb_x_offset = new QLineEdit(tab_3);
        tb_x_offset->setObjectName(QString::fromUtf8("tb_x_offset"));
        tb_x_offset->setGeometry(QRect(290, 10, 101, 21));
        tb_y_offset = new QLineEdit(tab_3);
        tb_y_offset->setObjectName(QString::fromUtf8("tb_y_offset"));
        tb_y_offset->setGeometry(QRect(290, 40, 101, 21));
        tb_z_offset = new QLineEdit(tab_3);
        tb_z_offset->setObjectName(QString::fromUtf8("tb_z_offset"));
        tb_z_offset->setGeometry(QRect(290, 70, 101, 21));
        label_18 = new QLabel(tab_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(400, 10, 47, 13));
        label_19 = new QLabel(tab_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(400, 40, 47, 13));
        label_20 = new QLabel(tab_3);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(400, 70, 47, 13));
        bt_gcode_configure = new QPushButton(tab_3);
        bt_gcode_configure->setObjectName(QString::fromUtf8("bt_gcode_configure"));
        bt_gcode_configure->setGeometry(QRect(290, 130, 80, 21));
        tb_hold_roll_angle = new QLineEdit(tab_3);
        tb_hold_roll_angle->setObjectName(QString::fromUtf8("tb_hold_roll_angle"));
        tb_hold_roll_angle->setGeometry(QRect(290, 100, 101, 21));
        label_21 = new QLabel(tab_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(400, 100, 47, 13));
        label_36 = new QLabel(tab_3);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(180, 40, 101, 21));
        label_37 = new QLabel(tab_3);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(10, 120, 101, 21));
        tw_method_content->addTab(tab_3, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        tb_conveyor_sp = new QLineEdit(tab_8);
        tb_conveyor_sp->setObjectName(QString::fromUtf8("tb_conveyor_sp"));
        tb_conveyor_sp->setGeometry(QRect(20, 10, 81, 21));
        bt_conveyor_sp = new QPushButton(tab_8);
        bt_conveyor_sp->setObjectName(QString::fromUtf8("bt_conveyor_sp"));
        bt_conveyor_sp->setGeometry(QRect(260, 10, 41, 21));
        label_42 = new QLabel(tab_8);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(110, 10, 121, 21));
        tb_p2p_1 = new QLineEdit(tab_8);
        tb_p2p_1->setObjectName(QString::fromUtf8("tb_p2p_1"));
        tb_p2p_1->setGeometry(QRect(20, 50, 81, 21));
        tb_p2p_2 = new QLineEdit(tab_8);
        tb_p2p_2->setObjectName(QString::fromUtf8("tb_p2p_2"));
        tb_p2p_2->setGeometry(QRect(20, 90, 81, 21));
        tb_p2p_3 = new QLineEdit(tab_8);
        tb_p2p_3->setObjectName(QString::fromUtf8("tb_p2p_3"));
        tb_p2p_3->setGeometry(QRect(20, 130, 81, 21));
        tb_p2p_4 = new QLineEdit(tab_8);
        tb_p2p_4->setObjectName(QString::fromUtf8("tb_p2p_4"));
        tb_p2p_4->setGeometry(QRect(20, 170, 81, 21));
        tb_p2p_5 = new QLineEdit(tab_8);
        tb_p2p_5->setObjectName(QString::fromUtf8("tb_p2p_5"));
        tb_p2p_5->setGeometry(QRect(20, 210, 81, 21));
        tb_p2p_10 = new QLineEdit(tab_8);
        tb_p2p_10->setObjectName(QString::fromUtf8("tb_p2p_10"));
        tb_p2p_10->setGeometry(QRect(250, 210, 81, 21));
        tb_p2p_7 = new QLineEdit(tab_8);
        tb_p2p_7->setObjectName(QString::fromUtf8("tb_p2p_7"));
        tb_p2p_7->setGeometry(QRect(250, 90, 81, 21));
        tb_p2p_8 = new QLineEdit(tab_8);
        tb_p2p_8->setObjectName(QString::fromUtf8("tb_p2p_8"));
        tb_p2p_8->setGeometry(QRect(250, 130, 81, 21));
        tb_p2p_9 = new QLineEdit(tab_8);
        tb_p2p_9->setObjectName(QString::fromUtf8("tb_p2p_9"));
        tb_p2p_9->setGeometry(QRect(250, 170, 81, 21));
        tb_p2p_6 = new QLineEdit(tab_8);
        tb_p2p_6->setObjectName(QString::fromUtf8("tb_p2p_6"));
        tb_p2p_6->setGeometry(QRect(250, 50, 81, 21));
        label_43 = new QLabel(tab_8);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(110, 50, 111, 21));
        label_44 = new QLabel(tab_8);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(110, 90, 121, 21));
        label_45 = new QLabel(tab_8);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(110, 130, 111, 21));
        label_46 = new QLabel(tab_8);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(110, 170, 101, 21));
        label_47 = new QLabel(tab_8);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(110, 210, 71, 16));
        label_48 = new QLabel(tab_8);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(340, 50, 61, 16));
        label_49 = new QLabel(tab_8);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(340, 210, 111, 21));
        label_50 = new QLabel(tab_8);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(340, 170, 121, 21));
        label_51 = new QLabel(tab_8);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(340, 90, 61, 21));
        label_52 = new QLabel(tab_8);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(340, 130, 51, 21));
        tw_method_content->addTab(tab_8, QString());
        gb_output_shaft = new QGroupBox(centralwidget);
        gb_output_shaft->setObjectName(QString::fromUtf8("gb_output_shaft"));
        gb_output_shaft->setGeometry(QRect(830, 280, 171, 51));
        bt_off_magnet = new QPushButton(gb_output_shaft);
        bt_off_magnet->setObjectName(QString::fromUtf8("bt_off_magnet"));
        bt_off_magnet->setGeometry(QRect(90, 20, 80, 21));
        bt_on_magnet = new QPushButton(gb_output_shaft);
        bt_on_magnet->setObjectName(QString::fromUtf8("bt_on_magnet"));
        bt_on_magnet->setGeometry(QRect(0, 20, 80, 21));
        bt_sw_test = new QPushButton(centralwidget);
        bt_sw_test->setObjectName(QString::fromUtf8("bt_sw_test"));
        bt_sw_test->setGeometry(QRect(50, 320, 80, 21));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1079, 20));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tw_method_content->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        bt_connect->setText(QCoreApplication::translate("MainWindow", "Connect", nullptr));
        bt_refresh->setText(QCoreApplication::translate("MainWindow", "Refresh", nullptr));
        gb_position_read->setTitle(QCoreApplication::translate("MainWindow", "Current position", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Roll", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "theta4", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "theta1", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "D3", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "theta2", nullptr));
        bt_read_position->setText(QCoreApplication::translate("MainWindow", "Read position", nullptr));
        rb_real_type->setText(QCoreApplication::translate("MainWindow", "Real Type", nullptr));
        rb_estimate_type->setText(QCoreApplication::translate("MainWindow", "Estimate Type", nullptr));
        cb_update_true_pos->setText(QCoreApplication::translate("MainWindow", "Update True Position", nullptr));
        bt_clear_console->setText(QCoreApplication::translate("MainWindow", "Clear console", nullptr));
        testing->setText(QCoreApplication::translate("MainWindow", "PushButton", nullptr));
        gb_method_change->setTitle(QCoreApplication::translate("MainWindow", "Change method", nullptr));
        rb_manual->setText(QCoreApplication::translate("MainWindow", "MANUAL", nullptr));
        rb_auto->setText(QCoreApplication::translate("MainWindow", "GCODE", nullptr));
        rb_test->setText(QCoreApplication::translate("MainWindow", "TEST", nullptr));
        rb_pick_and_place->setText(QCoreApplication::translate("MainWindow", "PICK AND PLACE", nullptr));
        rb_semi_auto->setText(QCoreApplication::translate("MainWindow", "SEMI-AUTO", nullptr));
        bt_set_method->setText(QCoreApplication::translate("MainWindow", "Set method", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "V factor(%)", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Time", nullptr));
        bt_movL->setText(QCoreApplication::translate("MainWindow", "Move", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "A factor", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Roll", nullptr));
        rb_movL->setText(QCoreApplication::translate("MainWindow", "MovL", nullptr));
        rb_movJ->setText(QCoreApplication::translate("MainWindow", "MovJ", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QCoreApplication::translate("MainWindow", "MovL-J", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        lb_1->setText(QCoreApplication::translate("MainWindow", "radius", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Time", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "V factor(%)", nullptr));
        bt_movC1->setText(QCoreApplication::translate("MainWindow", "Move Circle", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "A factor", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Roll", nullptr));
        rb_cw_c1->setText(QCoreApplication::translate("MainWindow", "CW(G02)", nullptr));
        rb_aw_c1->setText(QCoreApplication::translate("MainWindow", "AW(G03)", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QCoreApplication::translate("MainWindow", "MovC_Type1", nullptr));
        lb_2->setText(QCoreApplication::translate("MainWindow", "subpoint X", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        rb_aw_c2->setText(QCoreApplication::translate("MainWindow", "AW(G03)", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "Time", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "subpoint Y", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "A factor", nullptr));
        bt_movC2->setText(QCoreApplication::translate("MainWindow", "Move Circle", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "V factor(%)", nullptr));
        rb_cw_c2->setText(QCoreApplication::translate("MainWindow", "CW(G02)", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Roll", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QCoreApplication::translate("MainWindow", "MovC_Type2", nullptr));
        bt_robot_stop->setText(QCoreApplication::translate("MainWindow", "Stop", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindow", "Calculate model", nullptr));
        rb_qva->setText(QCoreApplication::translate("MainWindow", "QVA", nullptr));
        rb_qvt->setText(QCoreApplication::translate("MainWindow", "QVT", nullptr));
        rb_qt->setText(QCoreApplication::translate("MainWindow", "QT", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWindow", "Trajectory planning model", nullptr));
        rb_scur->setText(QCoreApplication::translate("MainWindow", "SCurve", nullptr));
        rb_lspb->setText(QCoreApplication::translate("MainWindow", "LSPB", nullptr));
        rb_linear->setText(QCoreApplication::translate("MainWindow", "Linear", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "Move method", nullptr));
        rb_inc->setText(QCoreApplication::translate("MainWindow", "Incremental", nullptr));
        rb_abs->setText(QCoreApplication::translate("MainWindow", "Absolute", nullptr));
        bt_home->setText(QCoreApplication::translate("MainWindow", "Move Home", nullptr));
        bt_scan_limit->setText(QCoreApplication::translate("MainWindow", "scan limit", nullptr));
        tw_method_content->setTabText(tw_method_content->indexOf(tab), QCoreApplication::translate("MainWindow", "SEMI-AUTO", nullptr));
        bt_inc_6->setText(QCoreApplication::translate("MainWindow", "Dec z", nullptr));
        bt_inc_2->setText(QCoreApplication::translate("MainWindow", "Dec x", nullptr));
        bt_inc_5->setText(QCoreApplication::translate("MainWindow", "Inc z", nullptr));
        bt_inc_7->setText(QCoreApplication::translate("MainWindow", "Inc roll", nullptr));
        bt_inc_8->setText(QCoreApplication::translate("MainWindow", "Dec roll", nullptr));
        bt_key_setsp->setText(QCoreApplication::translate("MainWindow", "Set key speed", nullptr));
        bt_inc_3->setText(QCoreApplication::translate("MainWindow", "Inc y", nullptr));
        bt_inc_1->setText(QCoreApplication::translate("MainWindow", "Inc x", nullptr));
        bt_inc_4->setText(QCoreApplication::translate("MainWindow", "Dec y", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Key speed(1-14)", nullptr));
        tw_method_content->setTabText(tw_method_content->indexOf(tab_7), QCoreApplication::translate("MainWindow", "MANUAL", nullptr));
        rb_test_mt4->setText(QCoreApplication::translate("MainWindow", "Motor4", nullptr));
        rb_test_mt2->setText(QCoreApplication::translate("MainWindow", "Motor2", nullptr));
        rb_test_mt1->setText(QCoreApplication::translate("MainWindow", "Motor1", nullptr));
        rb_test_mt3->setText(QCoreApplication::translate("MainWindow", "Motor3", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Negative", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Positive", nullptr));
        bt_start_test->setText(QCoreApplication::translate("MainWindow", "Start test", nullptr));
        bt_stop_test->setText(QCoreApplication::translate("MainWindow", "Stop test", nullptr));
        bt_model_setting->setText(QCoreApplication::translate("MainWindow", "Configure", nullptr));
        tb_m1_pulse->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        tb_m2_pulse->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        tb_m3_pulse->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        tb_m4_pulse->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Motor 1 pulse", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Motor 2 pulse", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "Motor 3 pulse", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Motor 4 pulse", nullptr));
        tw_method_content->setTabText(tw_method_content->indexOf(tab_2), QCoreApplication::translate("MainWindow", "TEST", nullptr));
        bt_browse->setText(QCoreApplication::translate("MainWindow", "Browse", nullptr));
        bt_process->setText(QCoreApplication::translate("MainWindow", "Process and send", nullptr));
        bt_gcode_pause->setText(QCoreApplication::translate("MainWindow", "Pause", nullptr));
        bt_gcode_resume->setText(QCoreApplication::translate("MainWindow", "Resume", nullptr));
        bt_gcode_stop->setText(QCoreApplication::translate("MainWindow", "Stop", nullptr));
        bt_gcode_start->setText(QCoreApplication::translate("MainWindow", "Start", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "offset X", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "offset Y", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "offset Z", nullptr));
        bt_gcode_configure->setText(QCoreApplication::translate("MainWindow", "Configure", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "roll angle", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Execute percentage", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Gcode file directory", nullptr));
        tw_method_content->setTabText(tw_method_content->indexOf(tab_3), QCoreApplication::translate("MainWindow", "GCODE", nullptr));
        tb_conveyor_sp->setText(QCoreApplication::translate("MainWindow", "37.5", nullptr));
        bt_conveyor_sp->setText(QCoreApplication::translate("MainWindow", "Set", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "Conveyor speed(mm/s", nullptr));
        tb_p2p_1->setText(QCoreApplication::translate("MainWindow", "0.301", nullptr));
        tb_p2p_2->setText(QCoreApplication::translate("MainWindow", "0.301", nullptr));
        tb_p2p_3->setText(QCoreApplication::translate("MainWindow", "0.301", nullptr));
        tb_p2p_4->setText(QCoreApplication::translate("MainWindow", "0.301", nullptr));
        tb_p2p_5->setText(QCoreApplication::translate("MainWindow", "1.201", nullptr));
        tb_p2p_10->setText(QCoreApplication::translate("MainWindow", "126.5", nullptr));
        tb_p2p_7->setText(QCoreApplication::translate("MainWindow", "0.0101", nullptr));
        tb_p2p_8->setText(QCoreApplication::translate("MainWindow", "131", nullptr));
        tb_p2p_9->setText(QCoreApplication::translate("MainWindow", "126.5", nullptr));
        tb_p2p_6->setText(QCoreApplication::translate("MainWindow", "0.0101", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "Put down time on slot", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "Put down time on object", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "Pick up time on object", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "Pick up time on slot", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "Move time", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "Attach time", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "Down height on slot", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "Down height on object", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "Detach time", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "Up Height", nullptr));
        tw_method_content->setTabText(tw_method_content->indexOf(tab_8), QCoreApplication::translate("MainWindow", "PICK-AND-PLACE", nullptr));
        gb_output_shaft->setTitle(QCoreApplication::translate("MainWindow", "Output shaft", nullptr));
        bt_off_magnet->setText(QCoreApplication::translate("MainWindow", "Magnet off", nullptr));
        bt_on_magnet->setText(QCoreApplication::translate("MainWindow", "Magnet on", nullptr));
        bt_sw_test->setText(QCoreApplication::translate("MainWindow", "Software test", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
